title: Mardené de Villiers   
       Curriculum Vitae (CV)    # You can add your name here

logo: image.png # Use a relative path to logo image 

description: Detail, data and science enthusiast. # Fix hyphenation 

email: mcdevilliers@gmail.com

darkmode: true

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

email: youremail@gmail.com # Allow visitors to contact you
