title: Mardené de Villiers  # You can add your name here

<logo: image.png width="50" height="50"> # Use a relative path to logo image 

description: Detail, data and science enthusiast. # Fix hyphenation 

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

email: youremail@gmail.com # Allow visitors to contact you
